import type { Metadata } from "next";
import { Geist, Geist_Mono, Jost } from "next/font/google";
import "./globals.css";
import HeroProvider from "../../providers/HeroProvider";

const JOST = Jost({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased ${JOST.className}`}
      >
        <HeroProvider>
          {children}
        </HeroProvider>
      </body>

    </html>
  );
}
