import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import HeroProvider from "../../providers/HeroProvider";
import NavBar from "../../components/section/NavBar";
import Footer from "../../components/section/Footer";

const JOST = Jost({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: "INNOVATION LABS ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased ${JOST.className}`}
      >
        <HeroProvider>
          <NavBar/>
          {children}
          <Footer/>
        </HeroProvider>
      </body>

    </html>
  );
}
